### ISSUE TITLE
怎么打包 app-plus？

### ISSUE THREAD

**Issue by dodu2014** [uni-helper/uni-deploy#10]
### 描述问题

可以打包 app-plus 吗，包括真机调试

### 复现

😎

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 15.00 GB / 23.92 GB
  Binaries:
    Node: 14.18.2 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.2 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
很遗憾，目前 uniapp 没有暴露相关的 API，无法实现。

**Comment by dodu2014** [comment]
好的，谢谢~~

**Comment by ModyQyW** [comment]
我们在考虑通过 https://hx.dcloud.net.cn/cli/pack?id=config 实现类似功能。请追踪 https://github.com/uni-helper/uni-deploy/issues/13。

**Comment by dodu2014** [comment]
@ModyQyW ，非常感谢，打包我已经实现 https://gitee.com/dodu/uniapp-starter
也是刚刚开源，运行到真机貌似 uniapp 并未开放

打包过程见 scripts 目录下：https://gitee.com/dodu/uniapp-starter/blob/master/scripts/hbx.pack.js
