### ISSUE TITLE
支持 HBuilderX CLI 打包 APP

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/uni-deploy#13]
<https://hx.dcloud.net.cn/cli/pack?id=config>

- 需要已经安装 HBuilderX
- uni-deploy 读取配置
- 如果没有给出 HBuilderX 安装目录，uni-deploy 尝试搜索 HBuilderX 目录并定位 CLI
  - Windows CLI 位置是 HBuilderX 安装目录下的 `cli.exe`
  - macOS CLI 位置是 `/Applications/HBuilderX.app/Contents/MacOS/cli`
- uni-deploy 自动唤起 HBuilderX
  - Windows 下 `cli.exe open`
  - macOS 下 `cli open` 
- uni-deploy 使用 shelljs 调用 cli 发起打包请求
- 打包完成，uni-deploy 视配置重命名文件

一些额外思考：

- 是否需要增加自动上传到指定 OSS？

**Comment by dodu2014** [comment]
https://gitee.com/dodu/uniapp-starter
支持 win 和 mac 脚本打包，不过需要自行配置环境变量，自动查找 HBuilderX 安装目录 并未实现

**Comment by ModyQyW** [comment]
如果愿意，欢迎在此提个 PR :D

**Comment by ModyQyW** [comment]
Not stale. Just having some bad days.
