### ISSUE TITLE
迁移到 unconfig

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/uni-deploy#2]
### 对问题的清晰和简明的描述

目前使用 [joycon](https://github.com/egoist/joycon)、[bundle-require](https://github.com/egoist/bundle-require) 和 [strip-json-comments](https://github.com/sindresorhus/strip-json-comments) 来读取配置文件，逻辑相对较长。

[unconfig](https://github.com/antfu/unconfig) 能显著减少代码，提高源码可读性。

### 推荐的解决方案

/

### 额外上下文

https://github.com/ModyQyW/uni-deploy-test

- 使用 unconfig 时，CLI 读取配置时会卡住不动。
- <del>使用 unconfig 时，vitest 测试会卡住不动。</del>

需要排查。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
刚刚我尝试切换到unconfig，通过了config.test.ts的测试

**Comment by ModyQyW** [comment]
确实能通过现有的测试，但是用 CLI 跑的时候就卡住了

我感觉是 unconfig 的问题，之前调了一两天没有头绪。等我晚点加点测试然后再调试一下好了

**Comment by ModyQyW** [comment]
可以试试 https://github.com/ModyQyW/uni-deploy-test

**Comment by KeJunMao** [comment]
确实复现了，貌似是因为 `jiti`导致的。一个可行的办法将 config 单独导出
```ts
import { defineConfig } from '@uni-helper/uni-deploy/config';

export default defineConfig({
  im: {
    wecom: {
      webhook: 'https://fake.wecom.webhook',
    },
  },
});
```

```bash
❯ nr validate
> uni-deploy validate
INFO [2022-11-19 09:58:41.025 +0800]: 没有配置微信小程序，跳过微信小程序操作。
```

**Comment by ModyQyW** [comment]
单独导出确实可以，但又降低了便捷性。如果可以，我还是倾向于直接从 uni-deploy 中导出

我忙完公司业务后再花点时间调试看看，然后去提个 PR 啥的

**Comment by ModyQyW** [comment]
https://github.com/unjs/jiti/issues/98

**Comment by ModyQyW** [comment]
依旧感觉不太稳定，暂时先搁置这个计划。
